// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgL5VqCBdHI43OXAKBuT39CwdZNqhwpWI',
    appId: '1:308765820717:android:6b9f702fa9b1a5362bf5a4',
    messagingSenderId: '308765820717',
    projectId: 'fir-first-dc45b',
    databaseURL: 'https://fir-first-dc45b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-first-dc45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sIMcuRUAiBxUkaoUS_qsuEJuOkXbel4',
    appId: '1:308765820717:ios:314939363bd0429d2bf5a4',
    messagingSenderId: '308765820717',
    projectId: 'fir-first-dc45b',
    databaseURL: 'https://fir-first-dc45b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-first-dc45b.appspot.com',
    iosClientId: '308765820717-0dhq18gmeq8feo3jlecp68pqpfb4cpr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationWithFirebase',
  );
}
